### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by chriseidhof** [BananaKit/BananaKit#6]

**Comment by dbgrandi** [comment]
![bananas](https://cloud.githubusercontent.com/assets/4033/5430544/9870fc6e-83e0-11e4-8b82-eb775461ebe0.png)

**Comment by dbgrandi** [comment]
Image was originally from [WikiMedia](http://commons.wikimedia.org/wiki/File:Bananas.svg)

License:`Public domain; no restrictions to use.`
